[metadata]
title = "Distributed Systems Blog"
url = "https://muratbuffalo.blogspot.com/"
timeout = 300
entrySelector = "#main > #page_body > #Blog1 > .blog-posts > .post-outer-container > .post-outer > .post"
titleSelector = ".post-title > a"
linkSelector = ".post-bottom > .jump-link > a"
dateSelector = ".post-header > .post-header-line-1 > .byline > .timestamp-link > time"
contentSelector = ".container > .post-snippet > .snippet-item"

[neverworkintheory]
title = "Most Recent It Will Never Work in Theory"
url = "https://neverworkintheory.org/"
timeout = 300
entrySelector = "body > .container > main > .page"
titleSelector = "p:nth-child(3) > strong > a"
contentSelector = "p:nth-child(4)"
linkSelector =  "p:nth-child(3) > strong > a"

[quanta-math]
title = "Quanta: Mathematics"
url = "https://www.quantamagazine.org/mathematics/"
timeout = 300
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"

[quanta-computer-science]
title = "Quanta: Computer Science"
url = "https://www.quantamagazine.org/computer-science/"
timeout = 300
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"

[quanta-physics]
title = "Quanta: Physics"
url = "https://www.quantamagazine.org/physics/"
timeout = 300
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"

[azure-big-data]
title = "Azure: Big Data"
url = "https://azure.microsoft.com/en-us/blog/topics/big-data/"
timeout = 300
entrySelector = "#main > section > div.row.row-size2 > div.column.medium-8 > div:nth-child(1) > div > div > article"
titleSelector = "h2 > a"
contentSelector = "p:nth-child(3)"
linkSelector = "h2 > a"
dateSelector = "p"

[azure-serverless]
title = "Azure: Serverless"
url = "https://azure.microsoft.com/en-us/blog/topics/serverless"
timeout = 300
entrySelector = "#main > section > div.row.row-size2 > div.column.medium-8 > div:nth-child(1) > div > div > article"
titleSelector = "h2 > a"
contentSelector = "p:nth-child(3)"
linkSelector = "h2 > a"
dateSelector = "p"

[azure-database]
title = "Azure: Database"
url = "https://azure.microsoft.com/en-us/blog/topics/database"
timeout = 300
entrySelector = "#main > section > div.row.row-size2 > div.column.medium-8 > div:nth-child(1) > div > div > article"
titleSelector = "h2 > a"
contentSelector = "p:nth-child(3)"
linkSelector = "h2 > a"
dateSelector = "p"

[azure-cloud-strategy]
title = "Azure: Cloud Strategy"
url = "https://azure.microsoft.com/en-us/blog/topics/cloud-strategy"
timeout = 300
entrySelector = "#main > section > div.row.row-size2 > div.column.medium-8 > div:nth-child(1) > div > div > article"
titleSelector = "h2 > a"
contentSelector = "p:nth-child(3)"
linkSelector = "h2 > a"
dateSelector = "p"