[default]
timeout = 600 # 10 minutes :o

[metadata]
title = "Distributed Systems Blog"
url = "https://muratbuffalo.blogspot.com/"
entrySelector = "#main > #page_body > #Blog1 > .blog-posts > .post-outer-container > .post-outer > .post"
titleSelector = ".post-title > a"
linkSelector = ".post-bottom > .jump-link > a"
dateSelector = ".post-header > .post-header-line-1 > .byline > .timestamp-link > time"
contentSelector = ".container > .post-snippet > .snippet-item"

[neverworkintheory]
title = "Most Recent It Will Never Work in Theory"
url = "https://neverworkintheory.org/"
entrySelector = "body > .container > main > .page"
titleSelector = "p:nth-child(3) > strong > a"
contentSelector = "p:nth-child(4)"
linkSelector =  "p:nth-child(3) > strong > a"

[quanta-math]
title = "Quanta: Mathematics"
url = "https://www.quantamagazine.org/mathematics/"
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"

[quanta-computer-science]
title = "Quanta: Computer Science"
url = "https://www.quantamagazine.org/computer-science/"
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"

[quanta-physics]
title = "Quanta: Physics"
url = "https://www.quantamagazine.org/physics/"
entrySelector = ".mha > .cws > .cws__content > div > .card"
titleSelector = ".card__content > a > h2"
contentSelector = ".card__excerpt > p"
linkSelector = ".card__content > a"
dateSelector = ".card__content > .card__meta > .card-date > div"